# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11eY7yCKwXNiUjgJWENQcJkCyWom2psli

Calculator
"""

def calc():
 x = float(input("enter the no 1  "))
 y = float(input("enter the no 2  "))
 z = input("enter the operator  ")
 if z == '+':
   print("the calculation is=",(x + y))
 elif z == '-':
   print("the calculation is=",(x - y))
 elif z == '*':
   print("the calculation is=",(x * y))
 elif z == '/':
   print("the calculation is=",(x / y))  
 else:
   print("invalid operator")
calc()

